version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "6603:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: test
      DB_PORT: 3306
    ports:
      - "8800:8800"
    command: /bin/sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm start"

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  mysql-data:
