backend:
  build:
    context: ./backend  
    dockerfile: Dockerfile
  depends_on:
    mysql:
      condition: service_healthy
  environment:
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: root
    DB_DATABASE: test
    DB_PORT: 3306
  ports:
    - "8800:8800"
  command: /bin/sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm start"
