# # services:
# #   mysql:
# #     image: mysql:8
# #     environment:
# #       MYSQL_ROOT_PASSWORD: root
# #       MYSQL_DATABASE: test
# #     ports:
# #       - "6603:3306"
# #     volumes:
# #       - mysql-data:/var/lib/mysql
# #     healthcheck:
# #       test: ["CMD", "mysqladmin", "ping", "--silent"]
# #       interval: 10s
# #       timeout: 5s
# #       retries: 5

# #   backend:
# #     image: 120717612929.dkr.ecr.us-east-1.amazonaws.com/my-app-backend:latest
# #     depends_on:
# #       mysql:
# #         condition: service_healthy
# #     environment:
# #       DB_HOST: mysql
# #       DB_USER: root
# #       DB_PASSWORD: root
# #       DB_DATABASE: test
# #       DB_PORT: 3306
# #     ports:
# #       - "8800:8800"

# #   frontend:
# #     image: 120717612929.dkr.ecr.us-east-1.amazonaws.com/my-app-frontend:latest
# #     ports:
# #       - "5173:5173"

# # volumes:
# #   mysql-data:
# services:
#   mysql:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
#     ports:
#       - "6603:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "--silent"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   backend:
#     build:
#       context: ./backend
#     depends_on:
#       mysql:
#         condition: service_healthy
#     environment:
#       DB_HOST: mysql
#       DB_USER: root
#       DB_PASSWORD: root
#       DB_DATABASE: test
#       DB_PORT: 3306
#     ports:
#       - "8800:8800"

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "5173:5173"

# volumes:
#   mysql-data:

version: "3.8"
services:
  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT}
    ports:
      - "8800:8800" 

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_BASE_URL: ${FRONTEND_URL}  
    ports:
      - "5173:5173"  

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     # If using SSL, mount your certificate files:
  #     - ./certs:/etc/nginx/certs:ro
  #   depends_on:
  #     - backend
  #     - frontend
