# # docker-compose.yml
# version: "3.8"
# services:
#   backend:
#     build:
#       context: ./backend
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_DATABASE: ${DB_DATABASE}
#       DB_PORT: ${DB_PORT}
#       FRONTEND_URL: "https://www.sufiyancreates.live"  
#       PORT: ${PORT}
#     ports:
#       - "8800:8800"

#   frontend:
#     build:
#       context: ./frontend
#     environment:
#       VITE_API_BASE_URL: "https://www.sufiyancreates.live/api" 
#     ports:
#       - "5173:5173"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - /etc/letsencrypt-docker:/etc/letsencrypt  # Mounting SSL certs inside Nginx
#     depends_on:
#       - backend
#       - frontend

# docker-compose.yml
version: "3.8"
services:
  backend:
    # Remove the build block and use the ECR image
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-app-backend:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
      - "8800:8800"

  frontend:
    # Remove the build block and use the ECR image
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-app-frontend:latest
    environment:
      VITE_API_BASE_URL: "https://www.sufiyancreates.live/api"
    ports:
      - "5173:5173"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt-docker:/etc/letsencrypt  # Mounting SSL certs inside Nginx
    depends_on:
      - backend
      - frontend